development:
 secret_key_base: f70ee484484eba777d563bf09baa55a78a3b8f43f5e15d28f3e3ab30cb52ef5a82bc7389824488bf5015c60041f34e7f868aadc544243c63b525a24bef70392f
 facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
 facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
test:
 secret_key_base: f70ee484484eba777d563bf09baa55a78a3b8f43f5e15d28f3e3ab30cb52ef5a82bc7389824488bf5015c60041f34e7f868aadc544243c63b525a24bef70392f
 facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
 facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
production:
 secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
 facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
 facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>